import os
import json
from dotenv import load_dotenv
from anthropic import Anthropic, BadRequestError

# Load environment variables
load_dotenv()
if "ANTHROPIC_API_KEY" not in os.environ:
    os.environ["ANTHROPIC_API_KEY"] = "dummy_key"

client = Anthropic()

def demonstrate_token_counting():
    """
    Shows how to use Anthropic's token counting API to proactively
    manage the context window and prevent HTTP 400 Bad Request errors.
    """
    print(f"{'='*80}")
    print("EXAMPLE 1: PROACTIVE TOKEN COUNTING (Preventing 400 Errors)")
    print(f"{'='*80}\n")
    
    # We construct a large prompt (simulating a long conversation history or large document)
    large_document = "The quick brown fox jumps over the lazy dog. " * 500
    
    messages = [
        {"role": "user", "content": f"Please analyze this document:\n\n{large_document}"}
    ]
    
    print("1. Estimating token size before hitting the model...")
    # Anthropic provides a count_tokens endpoint so you don't need a local tokenizer like tiktoken!
    # Note: We pass the exact model and messages array to get a highly accurate count.
    try:
        token_response = client.messages.count_tokens(
            model="claude-sonnet-4-5",
            messages=messages
        )
        print(f"   -> API confirmed payload is exactly {token_response.input_tokens} tokens.")
        
        # We can proactively check this against our known context limit
        CONTEXT_LIMIT = 200000 
        
        if token_response.input_tokens > CONTEXT_LIMIT * 0.9:
            print("   -> [DANGER]: Context window is almost full (>90%). Initiating truncation/summarization before sending!")
        else:
            print("   -> [SAFE]: Payload is well within the 200,000 token limit. Safe to send request.")
            
    except Exception as e:
        print(f"Error counting tokens: {e}")


def demonstrate_summarization_checkpoint():
    """
    Shows how to implement a 'Summarization Checkpoint' pattern.
    When a conversation history grows too large, we pause, summarize the history
    using a cheaper model, and compress it into a single message to free up the window.
    """
    print(f"\n\n{'='*80}")
    print("EXAMPLE 2: SUMMARIZATION CHECKPOINT PATTERN (Sliding Window Compression)")
    print(f"{'='*80}\n")
    
    # Simulating a very long conversation log with a user
    simulated_history = [
        {"role": "user", "content": "Hello, I am building a microservices architecture."},
        {"role": "assistant", "content": "Great, what languages are you using?"},
        {"role": "user", "content": "I'm using Python for the backend and React for the frontend."},
        {"role": "assistant", "content": "Excellent choices. What about your database?"},
        {"role": "user", "content": "We are evaluating PostgreSQL and MongoDB."},
        {"role": "assistant", "content": "PostgreSQL is great for relational data, MongoDB for document storage. Which fits better?"},
        {"role": "user", "content": "Our data is highly relational, so we'll go with PostgreSQL."}
    ]
    
    # In a real app, you would check `count_tokens` dynamically. 
    # For this demo, we assume the history hit our arbitrary threshold.
    print("1. Simulated conversation history hit our token threshold (e.g., 10,000 tokens).")
    print("2. Triggering a Summarization Checkpoint...")
    
    # We ask the model to summarize the history
    # Typically, you can use a cheaper, faster model like Haiku for this step to save costs!
    history_text = json.dumps(simulated_history, indent=2)
    summarization_prompt = f"Please summarize the following conversation history into a concise block of context. Retain all key technical decisions made by the user:\n\n{history_text}"
    
    try:
        summary_response = client.messages.create(
            # Using the required model for this workspace
            model="claude-sonnet-4-5", 
            max_tokens=300,
            messages=[{"role": "user", "content": summarization_prompt}]
        )
        summary = summary_response.content[0].text
        
        print(f"\n[Original History Length]: ~{len(history_text)} characters")
        print(f"[Summarized History Length]: ~{len(summary)} characters\n")
        print(f"[Compressed Context Block Generated by Haiku]:\n{summary}\n")
        
        # We now replace the entire raw history array with this single compressed message
        compressed_messages = [
            {"role": "user", "content": f"Here is the context of our conversation so far:\n<context>\n{summary}\n</context>\n\nNow, how should I deploy this stack to AWS?"}
        ]
        
        print("3. Replaced raw history with the new summary block.")
        print("4. Continuing the conversation with massive context window savings!")
        
    except Exception as e:
        print(f"Error during summarization: {e}")

if __name__ == "__main__":
    demonstrate_token_counting()
    demonstrate_summarization_checkpoint()
