"""
Well-Defined Tools

Provides best practices for defining tool schemas and descriptions to ensure
the model uses them correctly and reliably. Good tool descriptions are often
more important than the prompt itself in guiding the model's behavior.
"""

import os
import json
from dotenv import load_dotenv
from anthropic import Anthropic

# Constants
DEFAULT_MODEL = "claude-haiku-4-5"


# Load environment variables (API Key)
load_dotenv()
if "ANTHROPIC_API_KEY" not in os.environ:
    os.environ["ANTHROPIC_API_KEY"] = "dummy_key"
client = Anthropic()

# =====================================================================
# ❌ VAGUE TOOL DEFINITION (Causes Hallucinations & Schema Violations)
# =====================================================================
vague_tool = {
    "name": "update_customer_record",
    "description": "Updates a customer record with given fields.",
    "input_schema": {
        "type": "object",
        "properties": {
            "customer_id": {"type": "string"},
            "fields": {"type": "object"}
        },
        "required": ["customer_id"]
    }
}


# =====================================================================
# ✅ RECOMMENDED: Production Tool Definition (Clear Boundaries & Formats)
# =====================================================================
well_defined_tool = {
    "name": "update_customer_record",
    # Clear description explaining intent AND boundary behaviors (partial updates)
    "description": (
        "Updates specific fields of an existing customer record (partial updates supported). "
        "Only provided fields will be modified; omitted fields remain unchanged. "
        "Do NOT pass fields outside the explicit schema properties."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "customer_id": {
                "type": "string",
                "description": "The unique customer UUID (e.g., 'cust_12345')."
            },
            "email": {
                "type": "string",
                "format": "email",
                "description": "Updated primary email address. Must be valid email format."
            },
            "phone_number": {
                "type": "string",
                "description": "E.164 formatted phone number (e.g., '+14155552671')."
            },
            "status": {
                "type": "string",
                "enum": ["active", "suspended", "archived"],
                "description": "Account status flag. Must be one of the allowed enum values."
            }
        },
        # Strictly require customer_id; all other fields are optional for partial updates
        "required": ["customer_id"],
        # Prevents extra non-schema fields when using Strict Tool Mode
        "additionalProperties": False
    }
}


# =====================================================================
# API Call Demonstration
# =====================================================================
def run_tool_call_example():
    user_prompt = "Change customer cust_98765's status to active and update their email to jane@example.com."
    
    print("=" * 80)
    print("🔧 RUNNING WELL-DEFINED TOOL EXAMPLE")
    print("=" * 80)
    print(f"User Prompt: '{user_prompt}'\n")

    response = client.messages.create(
        model=DEFAULT_MODEL,
        max_tokens=1024,
        tools=[well_defined_tool],
        messages=[{"role": "user", "content": user_prompt}]
    )

    # Inspect the tool call generated by Claude
    for block in response.content:
        if block.type == "tool_use":
            print(f"Tool Name Triggered: {block.name}")
            print("Generated Input Payload (Note how it respects boundaries & enum values):")
            print("-" * 60)
            print(json.dumps(block.input, indent=2))
            print("-" * 60)

if __name__ == "__main__":
    run_tool_call_example()
